project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd" # this must be here!
    - "!code_py/"
    - "!code_r/"

website:
  page-navigation: true
  title: "Real World Acumen"

  navbar:
    left:
      - href: business/index.qmd
        text: Business

      - href: ds/index.qmd
        text: DS & Stat
        
    right: 
      - icon: github
        href: https://github.com/andreaczhang/rwacumen
        
format:
  html:
    theme: lux
    # css: styles.css
    toc: true

